daily_scheduler/urls.py
from django.conf.urls import url
from django.contrib import admin
import schedules
from schedules import views
from django.conf.urls import url,include


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r"^", include("schedules.urls", namespace="schedules")),
    
]

schedules/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^$",views.schedule_list, name="list"),
    url(r"^schedule/(?P<schedule_id>\d+)/$",views.schedule_show, name="show"),
    url(r"^schedule/(?P<schedule_id>\d+)/activities/(?P<activity_id>\d+)$",views.activity_delete, name="activity-delete"),
    url(r"^schedule/(?P<schedule_id>\d+)/activities/$",views.activity_create, name="activity-create"),
]

schedules/models.py
from __future__ import unicode_literals

from django.db import models
from django.core.validators import MaxValueValidator,MinValueValidator
from django.core.exceptions import ValidationError
# Create your models here.

class Schedule(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    name = models.CharField(blank=True, max_length=20)
    
    def __str__(self):
        return "%s - %s" % (self.created_at.date(), self.name)
    

class Activity(models.Model):
    name = models.CharField(blank=False,null=False,max_length=20)
    schedule = models.ForeignKey(Schedule, on_delete=models.CASCADE)
    rank = models.IntegerField(
                    default=1,
                    validators=[MaxValueValidator(5), MinValueValidator(1)]
                 )
    start = models.TimeField()
    end = models.TimeField()
    
    def clean(self,*args,**kwargs):
        if self.start>=self.end:
            raise ValidationError(
                ('start-time: %(start)s must be less than end-time: %(end)s'),
                params={'start': self.start, 'end':self.end},
            )

    def __str__(self):
        return "%s - %s:%s" % (self.name, self.start, self.end)
        

schedules/forms.py
from django.forms import ModelForm
from django.forms.models import inlineformset_factory

from django import forms
from .models import Schedule, Activity


from django.forms import BaseFormSet
from django.forms import formset_factory

class ScheduleForm(ModelForm):
    class Meta:
        model = Schedule
        fields = ['name']

class ActivityForm(ModelForm):
    class Meta:
        model = Activity
        exclude=['schedule']

schedules/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import Http404

from django.shortcuts import render, get_object_or_404, redirect
from django.forms import formset_factory
from .models import Schedule, Activity
from .forms import ScheduleForm, ActivityForm
# Create your views here.

def schedule_list(request):
    if request.method=="POST":
        f = ScheduleForm(request.POST)
        if f.is_valid():
            stmt = f.save()
        else:
            raise Http404
    new_form = ScheduleForm()
    
    all_schedules = Schedule.objects.all()
    params = {'schedules':all_schedules,'schedule_form':new_form}
    return render(request,'schedule_list.html',params)
    
def schedule_show(request,schedule_id):
    schedule=get_object_or_404(Schedule,id=schedule_id)
    if request.method == "POST":
        schedule.delete()
        return redirect("schedules:list")
    activities = schedule.activity_set.order_by('start').all()
    params = {
        'schedule':schedule,
        'activities': activities
    }
    return render(request,'schedule_show.html',params)

def activity_delete(request,schedule_id,activity_id):
    # TODO check if given activity belongs to schedule
    activity = get_object_or_404(Activity,id=activity_id)
    activity.delete()
    return redirect(reverse("schedules:show", kwargs={'schedule_id':schedule_id}))
    

def activity_create(request,schedule_id):
    schedule=get_object_or_404(Schedule,id=schedule_id)
    if request.method=="POST":
        
        f = ActivityForm(request.POST)
        if f.is_valid():
            stmt = f.save(commit=False)
            stmt.schedule_id = schedule_id
            stmt.save()
            return redirect(reverse("schedules:show", kwargs={'schedule_id':schedule_id}))
        else:
            raise Http404
    activity_form = ActivityForm()
    
    params = {
        'schedule_id':schedule.id,
        'activity_form': activity_form
    }
    return render(request,'activity_create.html', params)
    

templates/activity_create.html
<h1>create a new activity!</h1>

<form method="post" action="">
    {% csrf_token %}
    <table>
        {{ activity_form }}
    </table>
    <input type="submit" value="New Activity" class="">
</form>

templates/schedule_list.html
<h1>create a new schedule!</h1>



</form>
    <form method="POST">
        {% csrf_token %}
        {{ schedule_form }}
        <input type="submit" value="New Schedule" class="">
    </form>
<ul>
    {% for schedule in schedules %}
        <li><a href="{% url 'schedules:show' schedule_id=schedule.id %}">{{schedule.name }}: {{schedule.created_at}}</a> </li>
    {% endfor %}    
<ul/>



    

templates/schedule_show.html
<h1>{{schedule.name}}</h1>
{% if activities %}
<table>
    <tr>
        <th>name</th>
        <th>start time</th> 
        <th>end time</th>
        <th>importance</th>
        <th>delete</th>
      </tr>
    {% for activity in activities %}
      <tr>
          <td>{{activity.name}}</td> 
          <td>{{activity.start}}</td> 
          <td>{{activity.end}}</td> 
          <td>{{activity.rank}}</td> 
          <td>
              <form action="{% url 'schedules:activity-delete' schedule_id=schedule.id activity_id=activity.id %}"  method="POST">
                {% csrf_token %}
                {{ schedule_form }}
                <input type="submit" value="delete activity" class="">
              </form>
        </td> 
    </tr>  
    {% endfor %}
    <tr>
        <td><a href="{% url 'schedules:activity-create' schedule_id=schedule.id %}">add activity</td>
    </tr>
</table>
{%else %}
 <p>you have no activities yet please <a href="{% url 'schedules:activity-create' schedule_id=schedule.id %}">add one</a>!</p>
{% endif %}



    
<form method="POST">
    {% csrf_token %}
    {{ schedule_form }}
    <input type="submit" value="delete schedule" class="">
</form>